Sofi back
GianPolastri/BookVerse-API pull request #20
Opened 2023-07-29 02:54 UTC by sofiaparraweb

cambios para rutas review!!

2023-07-29 02:54 UTC, GonzaBerdazaiz approved these changes

2023-07-29 02:55 UTC, PedroFedeCasillas approved these changes

2023-07-29 18:56 UTC, GianPolastri approved these changes

2023-07-31 03:20 UTC, GianPolastri requested changes
Falta actualizar con un git pull

2023-08-03 14:40 UTC, closed without merging